# Generated by Django 4.0.4 on 2022-06-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcontroller', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='network',
            name='status',
            field=models.CharField(default='INACTIVE', max_length=32),
        ),
    ]
