# Generated by Django 4.0.4 on 2022-06-14 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcontroller', '0002_alter_network_status'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='network',
            name='zone_name_unique',
        ),
        migrations.RenameField(
            model_name='network',
            old_name='available_zone_hints',
            new_name='availability_zone_hints',
        ),
        migrations.AddConstraint(
            model_name='network',
            constraint=models.UniqueConstraint(fields=('availability_zone_hints', 'name'), name='zone_name_unique'),
        ),
    ]
