# Generated by Django 4.0.4 on 2022-06-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('netcontroller', '0003_remove_network_zone_name_unique_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='port',
            constraint=models.UniqueConstraint(fields=('ip', 'subnet_id'), name='ip_subnet_id_unique'),
        ),
    ]
